EnableSnowChangeEvents: true
PreventAllSnowForming: false
EnableLightningDetection: true
EnableChatListener: true
EnableTargetListener: true
EnableForgeHooks: true
EnableMoCreaturesHooks: true
EnableThaumcraftHooks: true
EnableTConstructHooks: true
EnableTFHooks: true
blacklisted-items:
    - MINEFACTORYRELOADED_NEEDLEGUNAMMOSTANDARD
    - MINEFACTORYRELOADED_NEEDLEGUNAMMOLAVA
    - MINEFACTORYRELOADED_NEEDLEGUNAMMOFIRE
    - MINEFACTORYRELOADED_NEEDLEGUNAMMOSLUDGE
    - MINEFACTORYRELOADED_NEEDLEGUNAMMOANVIL
    - MINEFACTORYRELOADED_NEEDLEGUNAMMOSEWAGE
    - MINEFACTORYRELOADED_NEEDLEGUNAMMOPIERCE
    - MINEFACTORYRELOADED_ROCKET
    - MINEFACTORYRELOADED_ROCKETLAUNCHER
    - MINEFACTORYRELOADED_NEEDLEGUN    
    - THAUMCRAFT_FOCUSPRIMAL
build-interact-items:
    - BUILDCRAFTTRANSPORT_PIPEPLUG
    - BUILDCRAFTTRANSPORT_PIPEGATE
    - BUILDCRAFTTRANSPORT_PIPEFACADE
    - BUILDCRAFTCORE_PAINTBRUSH
    - BUILDCRAFT_WRENCHITEM
    - CARPENTERSBLOCKS_ITEMCARPENTERSHAMMER
    - CARPENTERSBLOCKS_ITEMCARPENTERSCHISEL
    - IC2_ITEMTOOLMININGLASER
    - IC2_ITEMDYNAMITE
    - IC2_ITEMREMOTE
    - IC2_ITEMTOOLWRENCH
    - IC2_PLASMALAUNCHER
    - IC2_ITEMWEEDINGTROWEL
    - IC2_ITEMFOAMSPRAYER
    - IC2_ITEMTOOLPAINTER
    - IC2_ITEMTOOLPAINTERBLACK
    - IC2_ITEMTOOLPAINTERRED
    - IC2_ITEMTOOLPAINTERGREEN
    - IC2_ITEMTOOLPAINTERBROWN
    - IC2_ITEMTOOLPAINTERBLUE
    - IC2_ITEMTOOLPAINTERPURPLE
    - IC2_ITEMTOOLPAINTERCYAN
    - IC2_ITEMTOOLPAINTERLIGHTGREY
    - IC2_ITEMTOOLPAINTERDARKGREY
    - IC2_ITEMTOOLPAINTERPINK
    - IC2_ITEMTOOLPAINTERLIME
    - IC2_ITEMTOOLPAINTERYELLOW
    - IC2_ITEMTOOLPAINTERCLOUD
    - IC2_ITEMTOOLPAINTERMAGENTA
    - IC2_ITEMTOOLPAINTERORANGE
    - IC2_ITEMTOOLPAINTERWHITE
    - MINEFACTORYRELOADED_SAFARINETREUSABLE
    - MINEFACTORYRELOADED_SAFARINETSINGLEUSE
    - MINEFACTORYRELOADED_SAFARINETJAILERFANCY
    - MINEFACTORYRELOADED_SAFARINETJAILER
    - MINEFACTORYRELOADED_ROCKETLAUNCHER
    - MINEFACTORYRELOADED_SPYGLASS
    - MINEFACTORYRELOADED_NEEDLEGUN
    - MINEFACTORYRELOADED_POTATOLAUNCHER
    - MINEFACTORYRELOADED_SYRINGEHEALTH
    - MINEFACTORYRELOADED_SYRINGEEMPTY
    - MINEFACTORYRELOADED_SYRINGESLIME
    - MINEFACTORYRELOADED_SYRINGEGROWTH
    - MINEFACTORYRELOADED_STRAW
    - MINEFACTORYRELOADED_XPEXTRACTOR
    - RAILCRAFT_TOOLCROWBAR
    - RAILCRAFT_TOOLCROWBARMAGIC
    - RAILCRAFT_TOOLCROWBARREINFORCED
    - RAILCRAFT_TOOLCROWBARVOID
    - THERMALEXPANSION_CHILLER
    - THERMALEXPANSION_IGNITER
    - THERMALEXPANSION_WRENCH
    - THERMALEXPANSION_FLORB
    - THERMALEXPANSION_PUMP
    - THERMALEXPANSION_TOOLBATTLEWRENCHINVAR
    - THERMALDYNAMICS_RETRIEVER
    - THERMALDYNAMICS_RELAY
    - THERMALDYNAMICS_FILTER
    - THERMALDYNAMICS_SERVO
    - THAUMCRAFT_WANDCASTING
    - THAUMCRAFT_FOCUSPRIMAL
    - MOCREATURES_STAFFTELEPORT
    - MOCREATURES_STAFFPORTAL
pvp-interact-items:
    - TCONSTRUCT_THROWINGKNIFE
    - TCONSTRUCT_SHURIKEN
    - TCONSTRUCT_JAVELIN
    - TCONSTRUCT_SHORTBOW
    - TCONSTRUCT_CROSSBOW
    - TCONSTRUCT_LONGBOW
    - THERMALFOUNDATION_TOOLBOWELECTRUM
    - THERMALFOUNDATION_TOOLBOWINVAR
    - THERMALFOUNDATION_TOOLBOWSILVER
    - THERMALFOUNDATION_TOOLBOWTIN
    - THERMALFOUNDATION_TOOLBOWLEAD
    - THERMALFOUNDATION_TOOLBOWBRONZE
    - THERMALFOUNDATION_TOOLBOWPLATINUM
    - THERMALFOUNDATION_TOOLBOWCOPPER
bucket-interact-items:
    - BUCKET
    - BUILDCRAFTENERGY_BUCKETOIL
    - BUILDCRAFTENERGY_BUCKETFUEL
    - THAUMCRAFT_ITEMBUCKETDEATH
    - THAUMCRAFT_ITEMBUCKETPURE
    - RAILCRAFT_FLUIDCREOSOTEBUCKET
    - MINEFACTORYRELOADED_BUCKETSEWAGE
    - MINEFACTORYRELOADED_BUCKETESSENCE
    - MINEFACTORYRELOADED_BUCKETMEAT
    - MINEFACTORYRELOADED_BUCKETPINKSLIME
    - MINEFACTORYRELOADED_BUCKETCHOCOLATEMILK
    - MINEFACTORYRELOADED_BUCKETMUSHROOMSOUP
    - MINEFACTORYRELOADED_BUCKETBIOFUEL
    - MINEFACTORYRELOADED_BUCKETSLUDGE
    - THERMALFOUNDATION_BUCKET
    - TCONSTRUCT_BUCKETS
container-block-items:
    - ALMURA_STORAGEBIRCH_STORAGE_CRATE
    - ALMURA_STORAGEDARK_OAK_STORAGE_CRATE
    - ALMURA_STORAGEDOCK_CHEST
    - ALMURA_STORAGEQUANTUM_CHEST
    - ALMURA_STORAGEOAK_STORAGE_CRATE
    - ALMURA_STORAGESPRUCE_STORAGE_CRATE
    - BIBLIOCRAFT_BIBLIOTABLE
    - BIBLIOCRAFT_BIBLIOCASE
    - BIBLIOCRAFT_BIBLIORACK
    - BIBLIOCRAFT_BIBLIOSHELF
    - BIBLIOCRAFT_ARMOR_STAND
    - BIBLIOCRAFT_BIBLIOSWORDPEDESTAL
    - BIBLIOCRAFT_BIBLIOLABEL
    - BIBLIOCRAFT_BIBLIOFANCYSIGN
    - RAILCRAFT_MACHINEGAMMA 
    - RAILCRAFT_MACHINEALPHA
    - RAILCRAFT_MACHINEBETA
    - RAILCRAFT_ANVIL
    - THERMALEXPANSION_CELL
    - THERMALEXPANSION_MACHINE
    - THERMALEXPANSION_TANK
    - THERMALEXPANSION_STRONGBOX
    - THERMALEXPANSION_DEVICE
    - THERMALEXPANSION_CACHE
    - THAUMCRAFT_BLOCKTABLE
    - THAUMCRAFT_BLOCKSTONEDEVICE
    - IC2_BLOCKMACHINE
    - IC2_BLOCKMACHINE2
    - IC2_BLOCKMACHINE3
    - IC2_BLOCKGENERATOR
    - IC2_BLOCKPERSONAL
    - IC2_BLOCKKINETICGENERATOR
    - MINEFACTORYRELOADED_MACHINE
    - MINEFACTORYRELOADED_MACHINEBLOCK
    - MINEFACTORYRELOADED_MACHINE0
    - MINEFACTORYRELOADED_MACHINE1
    - MINEFACTORYRELOADED_MACHINE2
    - BUILDCRAFTROBOTICS_ZONEPLAN
    - BUILDCRAFTROBOTICS_REQUESTER
    - BUILDCRAFTSILICON_LASERTABLEBLOCK
    - BUILDCRAFTBUILDERS_FILLERBLOCK
    - BUILDCRAFTBUILDERS_BUILDERBLOCK
    - BUILDCRAFTBUILDERS_ARCHITECTBLOCK
    - BUILDCRAFTBUILDERS_LIBRARYBLOCK
    - BUILDCRAFTFACTORY_AUTOWORKBENCHBLOCK
    - BUILDCRAFTFACTORY_REFINERBLOCK
    - BUILDCRAFTSILICON_PACKAGERBLOCK
    - BUILDCRAFTFACTORY_BLOCKHOPPER
    - TCONSTRUCT_SMELTERY
    - TCONSTRUCT_ARMORDRYINGRACK
    - TCONSTRUCT_TOOLSTATIONBLOCK
    - TCONSTRUCT_LAVATANK
    - TCONSTRUCT_SEAREDBLOCK
    - TCONSTRUCT_CRAFTINGSTATION
    - TCONSTRUCT_CRAFTINGSLAB
    - TCONSTRUCT_TOOLFORGEBLOCK
    - CARPENTERSBLOCKS_BLOCKCARPENTERSAFE
    - THAUMCRAFT_BLOCKJAR
    - IRONCHEST_BLOCKIRONCHEST
    - THAUMCRAFT_BLOCKCHESTHUNGRY
door-block-items:
    - MALISISDOORS_SALOON
    - MALISISDOORS_DOOR_ACACIA
    - MALISISDOORS_DOOR_JUNGLE
    - MALISISDOORS_DOOR_BIRCH
    - MALISISDOORS_DOOR_SPRUCE
    - MALISISDOORS_DOOR_DARK_OAK
    - MALISISDOORS_SHOJI_DOOR
    - MALISISDOORS_WOOD_SLIDING_DOOR
    - MALISISDOORS_FACTORY_DOOR
    - MALISISDOORS_SLIDING_TRAPDOOR
    - MALISISDOORS_CURTAIN
    - THAUMCRAFT_BLOCKARCANEDOOR